name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload APK
      uses: actions/upload-artifact@v2.1.4
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk

  distribute:

    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
    - name: Download APK
      uses: actions/download-artifact@v2.0.5
      id: download
      with:
        name: app
        path: ./
    - name: Distribute to App Center
      uses: wzieba/AppCenter-Github-Action@v1.2.1
      with:
        appName: MatyDesign2910/MyInvestments
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: Beta tester
        file: ${{steps.download.outputs.download-path}}/app-debug.apk
        notifyTesters: true